eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service-docker:9009/eureka/
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME}
